/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author HewPack
 */
public class factura_citas extends javax.swing.JFrame implements Printable {

    /**
     * Creates new form factura_citas
     */
    public factura_citas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bn_imprimir = new javax.swing.JButton();
        bn_salir = new javax.swing.JButton();
        bnconsulta = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txt_consulta = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lb_idcitas = new javax.swing.JLabel();
        lb_hora = new javax.swing.JLabel();
        lb_cedula = new javax.swing.JLabel();
        lb_especialidad = new javax.swing.JLabel();
        lb_precio = new javax.swing.JLabel();
        lb_fecha = new javax.swing.JLabel();
        lb_paciente = new javax.swing.JLabel();
        lb_medico = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bn_imprimir.setText("IMPRIMIR");
        bn_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn_imprimirActionPerformed(evt);
            }
        });
        getContentPane().add(bn_imprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 394, -1, -1));

        bn_salir.setText("SALIR");
        bn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn_salirActionPerformed(evt);
            }
        });
        getContentPane().add(bn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 394, -1, -1));

        bnconsulta.setText("CONSULTA");
        bnconsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnconsultaActionPerformed(evt);
            }
        });
        getContentPane().add(bnconsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 339, -1, -1));

        jLabel13.setText("BUSCAR:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 343, -1, -1));
        getContentPane().add(txt_consulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 340, 250, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("CLINICA \" CUIDA TU SALUD \" ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 44, 194, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/logo _clinica_imprecion.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 44, -1, 82));

        jLabel3.setText("AV. 25 DE JULIO Y FRANCISCO SEGURA");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 69, -1, -1));

        jLabel4.setText("TELF: 3-552 274");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 101, -1, -1));

        jLabel5.setText("N°CITA:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 162, -1, -1));

        jLabel6.setText("HORA:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 194, -1, -1));

        jLabel7.setText("CEDULA:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 226, -1, -1));

        jLabel8.setText("ESPECIALIDAD:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 258, -1, -1));

        jLabel9.setText("FECHA:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 162, -1, -1));

        jLabel10.setText("PRECIO:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 290, -1, -1));

        jLabel11.setText("PACIENTE:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 226, -1, -1));

        jLabel12.setText("MEDICO:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 258, -1, -1));
        jPanel1.add(lb_idcitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 162, 91, 14));
        jPanel1.add(lb_hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 194, 91, 14));
        jPanel1.add(lb_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 226, 91, 14));
        jPanel1.add(lb_especialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 258, 130, 14));
        jPanel1.add(lb_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 91, 20));
        jPanel1.add(lb_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 162, 90, 14));
        jPanel1.add(lb_paciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 226, 120, 14));
        jPanel1.add(lb_medico, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 255, 120, 17));

        jLabel14.setText("$");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 10, 20));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("___________________________________________________________________________");
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 620, -1));

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("___________________________________________________________________________");
        jLabel17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 620, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnconsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnconsultaActionPerformed
        // CONSULTA
      
        mostrarDatos(txt_consulta.getText());

    }//GEN-LAST:event_bnconsultaActionPerformed

    private void bn_imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn_imprimirActionPerformed
        // TODO add your handling code here:
        botonimprimircitas();
    }//GEN-LAST:event_bn_imprimirActionPerformed

    private void bn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn_salirActionPerformed
        // TODO add your handling code here:
         menu me = new menu();
         me.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_bn_salirActionPerformed
public void botonimprimircitas (){
        PrinterJob printerJob = PrinterJob.getPrinterJob();
        printerJob.setPrintable(this);
        if (printerJob.printDialog()){
            try{
                printerJob.print();
            }catch (PrinterException ex){
                JOptionPane.showMessageDialog(null, "ERROR! ", "Error\n" + ex, JOptionPane.INFORMATION_MESSAGE );
            }
        }
    }
    
    public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException{
        if (pageIndex == 0 ){
            Graphics2D g2d = (Graphics2D) graphics;
            g2d.translate(pageFormat.getImageableX() + 30, pageFormat.getImageableY() + 30);
            jPanel1.printAll(graphics);
            return PAGE_EXISTS;
        }
        else{
            return NO_SUCH_PAGE;
        }
    }
    
    void mostrarDatos(String valor){
    String sql="";
    sql="SELECT * FROM citas where cedula='"+ valor+"'";
    try{
        Statement st = conex.createStatement();
        ResultSet rs = st.executeQuery(sql);
        while (rs.next()){
            lb_idcitas.setText(rs.getString(1));
            lb_fecha.setText(rs.getString(2));
            lb_hora.setText(rs.getString(3));
            lb_paciente.setText(rs.getString(4));
            lb_cedula.setText(rs.getString(5));
            lb_precio.setText(rs.getString(6));
            lb_especialidad.setText(rs.getString(7));
            llenarespecialidad(lb_especialidad.getText());
            lb_medico.setText(rs.getString(8));  
            llenarmedicos(lb_medico.getText());
        }
    }catch(SQLException ex){
        System.out.println(ex.getMessage());
    }
}
void llenarespecialidad(String valor){
    try{
        Statement st= conex.createStatement();
        String sql="Select * from especialidades where id_especialidad='"+valor + "'";
        ResultSet rs=st.executeQuery(sql);
        while(rs.next()){
            lb_especialidad.setText(rs.getString(2));
        }
    }catch(SQLException exc){
        System.out.println(exc.getMessage());
    }
}
void llenarmedicos(String valor){
    try{
        Statement st= conex.createStatement();
        String sql="Select * from medicos where id_medico="+valor;
        ResultSet rs=st.executeQuery(sql);
        while(rs.next()){
            lb_medico.setText(rs.getString(3));
        }
    }catch(SQLException exc){
        System.out.println(exc.getMessage());
    }
}

/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(factura_citas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(factura_citas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(factura_citas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(factura_citas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new factura_citas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bn_imprimir;
    private javax.swing.JButton bn_salir;
    private javax.swing.JButton bnconsulta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_cedula;
    private javax.swing.JLabel lb_especialidad;
    private javax.swing.JLabel lb_fecha;
    private javax.swing.JLabel lb_hora;
    private javax.swing.JLabel lb_idcitas;
    private javax.swing.JLabel lb_medico;
    private javax.swing.JLabel lb_paciente;
    private javax.swing.JLabel lb_precio;
    private javax.swing.JTextField txt_consulta;
    // End of variables declaration//GEN-END:variables
     conexion con=new conexion();
     Connection conex=con.conexion();
}
